MONGODB_URI: 'mongodb+srv://nucleusadmin:eMPF9pgRy2UqJW3@imagedata.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000'
DATA_HOME: '/mnt/pollux/data/world_model'

META:
  -
    collection: 'bucket-256-1'
    type: 'parquet'
    image_col: 'media_path'
    text_col: 'caption'